name: "Docker Actions"

on:
  pull_request:
    types: [closed]

jobs:
  action:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1

      - name: "hello-action"
        uses: ./.github/actions/hello-world
        with:
          firstGreeting: "Learning Lab User"
          secondGreeting: "Mona the Octocat"
